/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

export const DEVICE_TYPE_LIST = [
  {
    label: "Lighting",
    groupLabel: "Lights",
    type: [
      "lightbulb",
      "lightbulb3",
      "lightbulb4",
      "lightbulb5",
      "lightstrip",
      "lightstrip1",
      "light",
    ],
    name: "Light",
    param: "Light",
    deviceType: ["1", "2"],
    icon: {
      lightbulb: { icon: "light-3" },
      lightbulb3: { icon: "light-1" },
      lightbulb4: { icon: "light-1" },
      lightbulb5: { icon: "light-1" },
      lightstrip: { icon: "light-5" },
      lightstrip1: { icon: "light-5" },
    },
    defaultIcon: "light-1",
    disabled: false,
    controlPanel: "light",
  },
  {
    label: "Socket",
    groupLabel: "Sockets",
    type: [
      "singleplug",
      "singleplug1u",
      "dualplug",
      "dualplug1u",
      "dualplug2u",
      "powerstrip",
      "powerstrip3o1u",
      "powerstrip3o2u",
      "powerstrip3o3u",
      "socket",
      "singlesocket",
    ],
    name: "Socket",
    param: "Socket",
    deviceType: ["40", "41", "42"],
    icon: {
      singleplug: { icon: "socket" },
      singleplug1u: { icon: "socket-5" },
      powerstrip: { icon: "socket-2" },
      dualplug: { icon: "socket-4" },
      dualplug1u: { icon: "socket-4" },
      dualplug2u: { icon: "socket-4" },
      powerstrip3o1u: { icon: "socket-2" },
      powerstrip3o2u: { icon: "socket-2" },
      powerstrip3o3u: { icon: "socket-2" },
      socket: { icon: "socket" },
      singlesocket: { icon: "socket" },
    },
    defaultIcon: "socket",
    disabled: false,
  },
  {
    label: "Switch",
    groupLabel: "Switch",
    type: ["switch1", "switch2", "switch3", "dimmerswitch", "switch"],
    name: "Switch",
    param: "Switch",
    deviceType: ["80", "81", "82", "83"],
    icon: {
      switch1: { icon: "switch" },
      switch2: { icon: "switch-2" },
      switch3: { icon: "switch-3" },
      dimmerswitch: { icon: "switch-4" },
      switch: { icon: "switch" },
    },
    defaultIcon: "switch",
    disabled: false,
    controlPanel: "switch",
  },
  {
    label: "Fan",
    groupLabel: "Fan",
    type: ["fan"],
    name: "Fan",
    param: "Fan",
    deviceType: 4,
    icon: {
      fan: { icon: "fan" },
    },
    defaultIcon: "fan",
    disabled: false,
  },
  {
    label: "Temperature",
    groupLabel: "Temperature",
    type: ["temperature-sensor"],
    name: "Temperature Sensor",
    param: "Temperature",
    deviceType: 5,
    icon: {
      temperature: { icon: "temperature" },
    },
    defaultIcon: "temperature",
    disabled: false
  },
  {
    label: "Sensor",
    groupLabel: "Sensor",
    type: ["sensor"],
    name: "Sensor",
    param: "Sensor",
    deviceType: 5,
    icon: {
      sensor: { icon: "sensor" },
    },
    defaultIcon: "sensor",
    disabled: true,
  },
  {
    label: "Router",
    groupLabel: "Router",
    type: ["router"],
    name: "Router",
    param: "Router",
    deviceType: 6,
    icon: {
      router: { icon: "router" },
    },
    defaultIcon: "router",
    disabled: true,
  },
  {
    label: "Garage Door",
    groupLabel: "Garage Door",
    type: ["garagedoor"],
    name: "Garage Door",
    param: "Garage Door",
    deviceType: 7,
    icon: {
      garagedoor: { icon: "garage-door" },
    },
    defaultIcon: "garage-door",
    disabled: true,
  },
  {
    label: "Watering",
    groupLabel: "Watering",
    type: ["watering"],
    name: "Watering",
    param: "Watering",
    deviceType: 8,
    icon: {
      watering: { icon: "watering" },
    },
    defaultIcon: "watering",
    disabled: true,
  },
  {
    label: "Espressif AI Agent",
    groupLabel: "AI Assistant",
    type: ["ai-assistant", 'AI Assistant', 'ai assistant'],
    name: "Espressif AI Agent",
    param: "Espressif AI Agent",
    icon: {
      "ai-assistant": { icon: "ai-assistant" },
      "AI Assistant": { icon: "ai-assistant" },
      "ai assistant": { icon: "ai-assistant" }
    },
    defaultIcon: "ai-assistant",
    disabled: false,
    controlPanel: "ai-agent",
  },
  {
    label: "Camera",
    groupLabel: "Camera",
    type: ["camera"],
    name: "Camera",
    param: "Camera",
    icon: {
      camera: { icon: "camera" },
    },
    defaultIcon: "camera",
    disabled: false,
    controlPanel: "camera",
  },
];
