# SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
#
# SPDX-License-Identifier: Apache-2.0
#

#!/usr/bin/env python3
"""
Generate config files from environment variables and .env for GitLab CI.
Uses .example files as templates (single source of truth); substitutes ${VAR}
and ${VAR:-default} from the environment, then writes the real config file.
Loads .env from repo root; never commit the generated files.
"""
import os
import re
from pathlib import Path

CONFIG_DIR = Path(__file__).resolve().parents[1] / "config"
REPO_ROOT = Path(__file__).resolve().parents[1]

# Placeholder pattern: ${VAR_NAME} or ${VAR_NAME:-default}
_ENV_PLACEHOLDER = re.compile(r"\$\{([A-Za-z0-9_]+)(?::-([^}]*))?\}")


def _substitute_env(template: str) -> str:
    """Replace ${VAR} and ${VAR:-default} in template with env values."""
    def repl(match: re.Match) -> str:
        key, default = match.group(1), match.group(2)
        if default is not None:
            value = os.environ.get(key, default)
        else:
            value = os.environ.get(key, "")
        return str(value) if value is not None else ""
    return _ENV_PLACEHOLDER.sub(repl, template)


def _generate_from_example(example_name: str, output_name: str) -> None:
    """Read example file, substitute env placeholders, write real config (do not commit)."""
    template_path = CONFIG_DIR / example_name
    output_path = CONFIG_DIR / output_name
    if not template_path.exists():
        raise FileNotFoundError(f"Template {template_path} not found")
    content = template_path.read_text(encoding="utf-8")
    header = "# Auto-generated by ci_setup_config.py - do not commit\n"
    output_path.write_text(header + _substitute_env(content), encoding="utf-8")
    print(f"Wrote {output_path}")


def _load_dotenv():
    """Load .env from repo root and parent dirs. Merges all; CI vars take precedence (only set if unset).
    When run from test/, loads esp-nova-home-app/.env for ANDROID_APP_APPLICATION_ID, IOS_APP_APPLICATION_ID, etc."""
    for base in (REPO_ROOT, REPO_ROOT.parent, REPO_ROOT.parent.parent):
        env_file = base / ".env"
        if env_file.exists():
            try:
                with open(env_file, "r") as f:
                    for line in f:
                        line = line.strip()
                        if line and not line.startswith("#") and "=" in line:
                            key, _, value = line.partition("=")
                            key = key.strip()
                            value = value.strip().strip('"').strip("'")
                            if key and key not in os.environ:
                                os.environ[key] = value
            except Exception:
                pass


def _env(key: str, default: str = "") -> str:
    return os.environ.get(key, default)


def _set_computed_env():
    """Set derived env vars so templates can use them (e.g. DEPLOYMENT_URI from BASE_URL + API_VERSION)."""
    if "DEPLOYMENT_URI" not in os.environ:
        base = _env("BASE_URL", "https://api.rainmaker.espressif.com").rstrip("/")
        api_ver = _env("API_VERSION", "v1").lstrip("/")
        default_uri = f"{base}/{api_ver}" if api_ver else base
        os.environ["DEPLOYMENT_URI"] = _env("DEPLOYMENT_URI", default_uri)
    if "ANDROID_PATH" not in os.environ and os.environ.get("ANDROID_HOME"):
        os.environ["ANDROID_PATH"] = os.environ["ANDROID_HOME"].rstrip("/")


def main():
    _load_dotenv()
    _set_computed_env()
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    _generate_from_example("deployment.yaml.example", "deployment.yaml")
    _generate_from_example("report_config.yaml.example", "report_config.yaml")
    _generate_from_example("app.yaml.example", "app.yaml")
    print("CI config generation complete.")


if __name__ == "__main__":
    main()
